### ISSUE TITLE
passing a tsconfig.json path to tsb.create no longer works for typescript 1.8.x

### ISSUE THREAD

**Issue by weinand** [jrieken/gulp-tsb#34] opened 2016-02-24 14:40 UTC
In this case tsb.create(path) returns a nop compilation function that returns null.

**Comment by idanov** [comment] 2016-03-13 13:13
@weinand are you experiencing it under OS X? Using it under Ubuntu works fine. However, it seems that `npm install gulp-tsb` installs different content for each platform and the problem is that in line 11 of the OS X version `fs_1.readFileSync(path, undefined);` should be `fs_1.readFileSync(path, 'utf-8');` instead. @jrieken what could be the reason that the same version of the package is delivering different content for different platforms?

**Comment by idanov** [comment] 2016-03-13 14:20
This seems to be the same issue as #36 
Btw I checked the latest `v1.10.2` on Ubuntu, the problem is there as well so not only OS X is affected.

**Comment by jrieken** [comment] 2016-03-14 08:25
it seems like a dup of https://github.com/jrieken/gulp-tsb/pull/33

**Comment by jrieken** [comment] 2016-04-13 07:18
fixed with either #33 or https://github.com/jrieken/gulp-tsb/commit/e28375af4f7375fb79bbc4d5e0d4f9d94ddb56ab

**Closed by jrieken** 2016-04-13 07:18 UTC
